### ISSUE TITLE
jQuery doesn't play the music

### ISSUE THREAD

**Issue by BeryllN** [jakecoffman/flask-tutorial#3]
Hey,
The code to play the songs in part 4 - music didn't work for me (and visibly others as well, according to the comments from the tutorial video).
I deleted `onclick="changeTrack('{{song}}')"` from the `a` tag and replaced the script by:
```html
	<script type='text/javascript'>
		{% for song in songs %}	
			$('li').click(function(){
				var str = $(this).text()
				$('audio').attr('src', '/static/music/'+str);
			});
		{% endfor %}
	</script>
```
which worked for me.
Cheers!

**Comment by jakecoffman** [comment]
Can you submit a pull request for this?

**Comment by BeryllN** [comment]
Hey,
I just made one, but I'm not sure it went well since it's the first time I'm doing this.
Cheers
